### ISSUE TITLE
Defeat dependency on Gordo

### ISSUE THREAD

**Issue by ryanjdillon** [equinor/latigo#14]
As per comments to be removed here:
https://github.com/equinor/latigo/blob/master/app/latigo/gordo/__init__.py#L86-L98

```python
# Defeat dependency on gordo
def _gordo_to_latigo_tag(gordo_tag: SensorTag) -> LatigoSensorTag:
    latigo_tag = LatigoSensorTag(gordo_tag.name, gordo_tag.asset)
    return latigo_tag


# Defeat dependency on gordo
def _gordo_to_latigo_tag_list(
    gordo_tag_list: typing.List[SensorTag]
) -> typing.List[LatigoSensorTag]:
    latigo_tag_list: typing.List[LatigoSensorTag] = []
    for gordo_tag in gordo_tag_list:
        latigo_tag = _gordo_to_latigo_tag(gordo_tag)
        latigo_tag_list.append(latigo_tag)
    return latigo_tag_list
```
Make latigo gordo-datatype agnostic? Feel free to correct me here Lennart :)

**Comment by mrdeveloperdude** [comment]
That comment should really be a docstring, because that function is doing exactly that.

The Tuple in gordo is called "SensorTag" while the Gordo agnostic version is "LatigoSensorTag". Anything outside the gordo file will only know about LatigoSensorTag.

This can thus safely be closed :-)
