### ISSUE TITLE
Fix `make up` altering app/latigo/clock.py

### ISSUE THREAD

**Issue by ryanjdillon** [equinor/latigo#6]
There is a commented line that is altered after having run `make up`, leaving the repo dirty.

**Comment by mrdeveloperdude** [comment]
?? Not sure what you mean?

**Comment by ryanjdillon** [comment]
It seems that file had a comment line that gets reformatting with the black call in `code_quality` Makefile, which adds a space, leaving that file modified. This should be fixed now with the updated formatting.
